################################################
# Make file generated by HEW
#

############################
# Toolchain directory define
# If incorrect, change to the location of the RX Standard Toolchain toolchain
TC_INSTALL_DIR = c:\program files (x86)\renesas\hew\tools\renesas\rx\1_2_1

#####################################################
#
# Details:
#   Project: Bontaco
#   Configuration: Release
#   Toolchain: Renesas RX Standard Toolchain
#
#####################################################

################
# Main Defines

# Renesas RX C/C++ Library Generator01 phase

BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXE=lbgrx.exe
BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR=$(TC_INSTALL_DIR)\bin
BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_OUTFILESC0="..\Bontaco\Release\Bontaco.lib"
BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_DEPFILESC0="$(TC_INSTALL_DIR)\bin\libinc_C89.pak"

# Renesas RX C/C++ Compiler02 phase

BONTACO_RELEASE_RX_CC_COMPILER02_EXE=ccrx.exe
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC0="..\Bontaco\Release\Bontaco.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC0="..\Bontaco\bontaco_main.h" "..\Bontaco\header\bontaco_init.h" "..\Bontaco\iodefine.h" \
	"..\Bontaco\header\bontaco_led.h" "..\Bontaco\bontaco_test.h" "..\Bontaco\header\bontaco_sci.h" \
	"..\Bontaco\header\bontaco_photosensor.h" "..\Bontaco\bontaco_timer.h" "..\Bontaco\header\bontaco_battery_watch.h" \
	"..\Bontaco\header\bontaco_encoder.h" "..\Bontaco\bontaco_common.h" "..\Bontaco\header\bontaco_motor_pwm.h" \
	"..\Bontaco\header\bontaco_buzzer.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC1="..\Bontaco\Release\Bontaco_main.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC1="..\Bontaco\header\bontaco_init.h" "..\Bontaco\iodefine.h" "..\Bontaco\header\bontaco_led.h" \
	"..\Bontaco\header\bontaco_sync.h" "..\Bontaco\bontaco_drive.h" "..\Bontaco\bontaco_common.h" \
	"..\Bontaco\header\bontaco_encoder.h" "..\Bontaco\header\bontaco_battery_watch.h" \
	"..\Bontaco\header\bontaco_sci.h" "..\Bontaco\header\bontaco_util.h" "$(TC_INSTALL_DIR)\include\stdarg.h" \
	"$(TC_INSTALL_DIR)\include\macro.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC2="..\Bontaco\Release\bontaco_drive.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC2="..\Bontaco\bontaco_drive.h" "..\Bontaco\iodefine.h" "..\Bontaco\bontaco_common.h" \
	"..\Bontaco\header\bontaco_encoder.h" "..\Bontaco\header\bontaco_battery_watch.h" \
	"..\Bontaco\header\bontaco_led.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC3="..\Bontaco\Release\bontaco_timer.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC3="..\Bontaco\bontaco_timer.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC4="..\Bontaco\Release\dbsct.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC4="..\Bontaco\typedefine.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC5="..\Bontaco\Release\bontaco_battery_watch.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC5="..\Bontaco\header\bontaco_battery_watch.h" "..\Bontaco\iodefine.h" "..\Bontaco\header\bontaco_led.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC6="..\Bontaco\Release\bontaco_buzzer.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC6="..\Bontaco\header\bontaco_buzzer.h" "..\Bontaco\iodefine.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC7="..\Bontaco\Release\bontaco_encoder.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC7="..\Bontaco\header\bontaco_encoder.h" "..\Bontaco\iodefine.h" "..\Bontaco\bontaco_common.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC8="..\Bontaco\Release\bontaco_init.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC8="..\Bontaco\header\bontaco_init.h" "..\Bontaco\iodefine.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC9="..\Bontaco\Release\bontaco_interrupt.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC9="..\Bontaco\header\bontaco_interrupt.h" "..\Bontaco\iodefine.h" "..\Bontaco\header\bontaco_led.h" \
	"..\Bontaco\header\bontaco_sync.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC10="..\Bontaco\Release\bontaco_led.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC10="..\Bontaco\header\bontaco_led.h" "..\Bontaco\iodefine.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC11="..\Bontaco\Release\bontaco_motor_pwm.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC11="..\Bontaco\header\bontaco_motor_pwm.h" "..\Bontaco\iodefine.h" "..\Bontaco\bontaco_common.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC12="..\Bontaco\Release\bontaco_photosensor.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC12="..\Bontaco\header\bontaco_photosensor.h" "..\Bontaco\iodefine.h" "..\Bontaco\header\bontaco_led.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC13="..\Bontaco\Release\bontaco_sci.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC13="$(TC_INSTALL_DIR)\include\stdarg.h" "$(TC_INSTALL_DIR)\include\macro.h" "..\Bontaco\header\bontaco_sci.h" \
	"..\Bontaco\iodefine.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC14="..\Bontaco\Release\bontaco_sync.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC14="..\Bontaco\header\bontaco_sync.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC15="..\Bontaco\Release\bontaco_util.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC15="..\Bontaco\header\bontaco_util.h" "$(TC_INSTALL_DIR)\include\stdarg.h" "$(TC_INSTALL_DIR)\include\macro.h" \
	"..\Bontaco\iodefine.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC16="..\Bontaco\Release\intprg.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC16="$(TC_INSTALL_DIR)\include\machine.h" "$(TC_INSTALL_DIR)\include\macro.h" "$(TC_INSTALL_DIR)\include\builtin.h" \
	"..\Bontaco\vect.h" "..\Bontaco\header\bontaco_interrupt.h" "..\Bontaco\iodefine.h" \
	"..\Bontaco\header\bontaco_led.h" "..\Bontaco\header\bontaco_buzzer.h" "..\Bontaco\header\bontaco_sci.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC17="..\Bontaco\Release\resetprg.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC17="$(TC_INSTALL_DIR)\include\machine.h" "$(TC_INSTALL_DIR)\include\macro.h" "$(TC_INSTALL_DIR)\include\builtin.h" \
	"$(TC_INSTALL_DIR)\include\_h_c_lib.h" "..\Bontaco\typedefine.h" "..\Bontaco\stacksct.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC18="..\Bontaco\Release\sbrk.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC18="$(TC_INSTALL_DIR)\include\stddef.h" "$(TC_INSTALL_DIR)\include\macro.h" "$(TC_INSTALL_DIR)\include\sys\yvals.h" \
	"$(TC_INSTALL_DIR)\include\stdarg.h" "$(TC_INSTALL_DIR)\include\errno.h" "$(TC_INSTALL_DIR)\include\stdio.h" \
	"..\Bontaco\typedefine.h" "..\Bontaco\sbrk.h"
BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC19="..\Bontaco\Release\vecttbl.obj"
BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC19="..\Bontaco\vect.h"

# Renesas RX Assembler03 phase

BONTACO_RELEASE_RX_ASSEMBLER03_EXE=asrx.exe

# Renesas OptLinker04 phase

BONTACO_RELEASE_OPTLINKER04_EXE=LnkSpawn.exe
BONTACO_RELEASE_OPTLINKER04_INFILESC0="..\Bontaco\Release\Bontaco.lib" "..\Bontaco\Release\Bontaco.obj" "..\Bontaco\Release\bontaco_battery_watch.obj" \
	"..\Bontaco\Release\bontaco_buzzer.obj" "..\Bontaco\Release\bontaco_drive.obj" "..\Bontaco\Release\bontaco_encoder.obj" \
	"..\Bontaco\Release\bontaco_init.obj" "..\Bontaco\Release\bontaco_interrupt.obj" \
	"..\Bontaco\Release\bontaco_led.obj" "..\Bontaco\Release\Bontaco_main.obj" "..\Bontaco\Release\bontaco_motor_pwm.obj" \
	"..\Bontaco\Release\bontaco_photosensor.obj" "..\Bontaco\Release\bontaco_sci.obj" \
	"..\Bontaco\Release\bontaco_sync.obj" "..\Bontaco\Release\bontaco_timer.obj" "..\Bontaco\Release\bontaco_util.obj" \
	"..\Bontaco\Release\dbsct.obj" "..\Bontaco\Release\intprg.obj" "..\Bontaco\Release\resetprg.obj" \
	"..\Bontaco\Release\sbrk.obj" "..\Bontaco\Release\vecttbl.obj"
BONTACO_RELEASE_OPTLINKER04_OUTFILESC0="..\Bontaco\Release\Bontaco.mot" "..\Bontaco\Release\Bontaco.abs" "..\Bontaco\Release\Bontaco.map"

#######################
# nmake "all" statement

ALL:	BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_ENVC0 \
	$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_OUTFILESC0) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC0) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC1) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC2) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC3) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC4) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC5) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC6) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC7) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC8) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC9) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC10) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC11) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC12) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC13) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC14) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC15) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC16) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC17) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC18) \
	$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC19) \
	$(BONTACO_RELEASE_OPTLINKER04_OUTFILESC0)

####################
# Description blocks

!MESSAGE
!MESSAGE Executing Renesas RX C/C++ Library Generator01 phase
!MESSAGE

BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_ENVC0 : 
	set INC_RX=$(TC_INSTALL_DIR)\include
	set PATH=$(TC_INSTALL_DIR)\bin
	set BIN_RX=$(TC_INSTALL_DIR)\bin
	set TMP_RX=C:\Users\Kento\AppData\Local\Temp

$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_OUTFILESC0) : $(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_DEPFILESC0)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXE)" -subcommand=<<
-cpu=rx200
-output="..\Bontaco\Release\Bontaco.lib"
-lang=c99
-head=runtime,ctype,math,stdarg,stdio,stdlib,string,new
<<

!MESSAGE
!MESSAGE Executing Renesas RX C/C++ Compiler02 phase
!MESSAGE

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC0) : "..\Bontaco\Bontaco.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC0)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\Bontaco.obj"
"..\Bontaco\Bontaco.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC1) : "..\Bontaco\Bontaco_main.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC1)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\Bontaco_main.obj"
"..\Bontaco\Bontaco_main.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC2) : "..\Bontaco\bontaco_drive.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC2)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_drive.obj"
"..\Bontaco\bontaco_drive.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC3) : "..\Bontaco\bontaco_timer.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC3)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_timer.obj"
"..\Bontaco\bontaco_timer.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC4) : "..\Bontaco\dbsct.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC4)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\dbsct.obj"
"..\Bontaco\dbsct.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC5) : "..\Bontaco\driver\bontaco_battery_watch.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC5)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_battery_watch.obj"
"..\Bontaco\driver\bontaco_battery_watch.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC6) : "..\Bontaco\driver\bontaco_buzzer.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC6)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_buzzer.obj"
"..\Bontaco\driver\bontaco_buzzer.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC7) : "..\Bontaco\driver\bontaco_encoder.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC7)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_encoder.obj"
"..\Bontaco\driver\bontaco_encoder.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC8) : "..\Bontaco\driver\bontaco_init.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC8)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_init.obj"
"..\Bontaco\driver\bontaco_init.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC9) : "..\Bontaco\driver\bontaco_interrupt.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC9)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_interrupt.obj"
"..\Bontaco\driver\bontaco_interrupt.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC10) : "..\Bontaco\driver\bontaco_led.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC10)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_led.obj"
"..\Bontaco\driver\bontaco_led.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC11) : "..\Bontaco\driver\bontaco_motor_pwm.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC11)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_motor_pwm.obj"
"..\Bontaco\driver\bontaco_motor_pwm.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC12) : "..\Bontaco\driver\bontaco_photosensor.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC12)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_photosensor.obj"
"..\Bontaco\driver\bontaco_photosensor.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC13) : "..\Bontaco\driver\bontaco_sci.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC13)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_sci.obj"
"..\Bontaco\driver\bontaco_sci.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC14) : "..\Bontaco\driver\bontaco_sync.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC14)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_sync.obj"
"..\Bontaco\driver\bontaco_sync.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC15) : "..\Bontaco\driver\bontaco_util.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC15)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\bontaco_util.obj"
"..\Bontaco\driver\bontaco_util.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC16) : "..\Bontaco\intprg.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC16)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\intprg.obj"
"..\Bontaco\intprg.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC17) : "..\Bontaco\resetprg.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC17)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\resetprg.obj"
"..\Bontaco\resetprg.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC18) : "..\Bontaco\sbrk.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC18)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\sbrk.obj"
"..\Bontaco\sbrk.c"
-nologo
<<

$(BONTACO_RELEASE_RX_CC_COMPILER02_OUTFILESC19) : "..\Bontaco\vecttbl.c" $(BONTACO_RELEASE_RX_CC_COMPILER02_DEPFILESC19)
	"$(BONTACO_RELEASE_RX_CC_LIBRARY_GENERATOR01_EXEDIR)\$(BONTACO_RELEASE_RX_CC_COMPILER02_EXE)" -subcommand=<<
-cpu=rx200
-lang=c
-include="..\Bontaco\header"
-include="..\Bontaco"
-output=obj="..\Bontaco\Release\vecttbl.obj"
"..\Bontaco\vecttbl.c"
-nologo
<<

!MESSAGE
!MESSAGE Executing Renesas OptLinker04 phase
!MESSAGE

$(BONTACO_RELEASE_OPTLINKER04_OUTFILESC0) : $(BONTACO_RELEASE_OPTLINKER04_INFILESC0)
	$(BONTACO_RELEASE_OPTLINKER04_EXE) -subcommand=<<
noprelink
nodebug
rom D=R,D_1=R_1,D_2=R_2
nomessage 
list "..\Bontaco\Release\Bontaco.map"
nooptimize
-start=B_1,R_1,B_2,R_2,B,R,SU,SI/01000,PResetPRG/0FFFF8000,C_1,C_2,C,C$*,D_1,D_2,D,P,PIntPRG,W*,L/0FFFF8100,FIXEDVECT/0FFFFFFD0
nologo
-input="..\Bontaco\Release\Bontaco.obj"
-input="..\Bontaco\Release\bontaco_battery_watch.obj"
-input="..\Bontaco\Release\bontaco_buzzer.obj"
-input="..\Bontaco\Release\bontaco_drive.obj"
-input="..\Bontaco\Release\bontaco_encoder.obj"
-input="..\Bontaco\Release\bontaco_init.obj"
-input="..\Bontaco\Release\bontaco_interrupt.obj"
-input="..\Bontaco\Release\bontaco_led.obj"
-input="..\Bontaco\Release\Bontaco_main.obj"
-input="..\Bontaco\Release\bontaco_motor_pwm.obj"
-input="..\Bontaco\Release\bontaco_photosensor.obj"
-input="..\Bontaco\Release\bontaco_sci.obj"
-input="..\Bontaco\Release\bontaco_sync.obj"
-input="..\Bontaco\Release\bontaco_timer.obj"
-input="..\Bontaco\Release\bontaco_util.obj"
-input="..\Bontaco\Release\dbsct.obj"
-input="..\Bontaco\Release\intprg.obj"
-input="..\Bontaco\Release\resetprg.obj"
-input="..\Bontaco\Release\sbrk.obj"
-input="..\Bontaco\Release\vecttbl.obj"
-library="..\Bontaco\Release\Bontaco.lib"
-output="..\Bontaco\Release\Bontaco.abs"
end
-input="..\Bontaco\Release\Bontaco.abs"
form stype
output "..\Bontaco\Release\Bontaco.mot"
-exit

<<

