/***********************************************************************/
/*                                                                     */
/*  FILE        :Bontaco.c                                             */
/*  DATE        :Sat, Nov 07, 2020                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX210                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  
#include "bontaco_init.h"
#include "bontaco_led.h"
#include "bontaco_test.h"

//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	init_rx220();
	
	check_battery();
	
//	test_debug_led();
//	test_mode_led();
	test_display();
//	test_sci();
//	test_sensor();
//	test_battery_watch(); 
//	test_encoder();
	test_motor();
	// test_buzzer();
	
	while(1);

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
