/***********************************************************************/
/*                                                                     */
/*  FILE        :Bontaco.c                                             */
/*  DATE        :Sat, Nov 07, 2020                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX210                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  
#include "bontaco_init.h"
#include "bontaco_led.h"
#include "bontaco_test.h"
#include "bontaco_flag.h"
#include "bontaco_drive.h"


static void handleEvent(void);
static void constantProcess(void);
static void main_loop(void);
static void sync_1ms(void);
void Main(void);

static void initialization(void)
{
	struct Motion motion = createMotionRunStraight(1000);
    turn_off_debug_led(0);
	turn_off_debug_led(1);
	turn_off_debug_led(2);
	turn_off_mode_led(0);	
	turn_off_mode_led(1);	

	display_7seg(10);

	// necessary to avoid weird rotation of left motor on enabling
	reset_encoder_count(LEFT);
	reset_encoder_count(RIGHT);

	check_battery();
	
	// test_debug_led();
	// test_mode_led();
	// test_display();
	// test_sci();
	// test_sensor();
	// test_battery_watch(); 
	// test_encoder();
	// test_motor();
	// test_run();
	// test_turn();
	// test_buzzer();
	
	enqueue(createMotionWait(1000));
	enqueue(createMotionRunStraight(200));
	enqueue(createMotion90turn(100, CW));
	enqueue(createMotionRunStraight(100));
	enqueue(createMotion90turn(100, CCW));
	enqueue(createMotionRunStraight(300));
	enqueue(createMotion90turn(200, CCW));
	enqueue(createMotion90turn(100, CW));
	setQueueTopToCurrentMotion();
	enable_motors();
}

static void handleEvent(void)
{
	if(isEndOfMotion()){
		if(queueIsEmpty()){
			brake();
		}else{
			dequeue();
			setQueueTopToCurrentMotion();
			ring_buzzer_for_ms(10);
		}
	}

}

static void constantProcess(void)
{
	update_encoder_diff(LEFT);
	update_encoder_diff(RIGHT);
	increment_timer_ms();
	decrement_buzzer_timer();
	execute_current_motion();
	pid_control_velocity();
	pid_control_angular_velocity();
	set_motor_duty_ratios();

}

static void main_loop(void)
{
	while(1){
		sync_1ms();

		handleEvent();

		constantProcess();
	}

}

static void sync_1ms(void)
{
	// check if 1ms flag is already set, i.e. loop process is not in time!
	if( getFlag() ){
		turn_on_debug_led(0);
		turn_on_debug_led(1);
		turn_on_debug_led(2);
	}
	// wait for 1ms flag to set
	while( !getFlag() );
	clearFlag();
}

void Main(void)
{
	initialization();

	main_loop();

}